name: verify

on: push

jobs:
  online-judge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run AOJ tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
  
  gtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up gtest
      run: git clone https://github.com/google/googletest.git && cd ./googletest && sudo cmake CMakeLists.txt && sudo make -j4 && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Run GoogleTest
      run: |
        cd ./GoogleTest
        ./gtest.sh